kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: nginx
    purpose: helm-demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.configmap.port }}
      